# Generated by Django 6.0.1 on 2026-01-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_networknode_supplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networknode",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="network_node",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="network.networknode",
            ),
        ),
    ]
